=== rbe/dmerce/dmerce3/etc/ncc.dtd
<!ELEMENT ncc (server*, service-group*, monitor*, redirector*)>
<!ELEMENT server (interface+, inet-service+)>
<!ELEMENT interface EMPTY>
<!ELEMENT inet-service (tcp+)>
<!ELEMENT tcp EMPTY>

<!ELEMENT service-group (service-group-member+)>
<!ELEMENT service-group-member EMPTY>
  
<!ELEMENT monitor (Service-group+, Server+)>
<!ELEMENT Service-group EMPTY>
<!ELEMENT Server EMPTY>
  
<!ELEMENT redirector (ip-from+, ip-to+)>
<!ELEMENT ip-from EMPTY>
<!ELEMENT ip-to EMPTY>

<!ELEMENT portscanner (network*,host*,port*)>
<!ELEMENT network (port*)>
<!ELEMENT host (port*)>
<!ELEMENT port EMPTY>

<!ATTLIST server
	name ID #REQUIRED
>

<!ATTLIST interface
    name CDATA #REQUIRED
	ip-address NMTOKEN #IMPLIED
>

<!ATTLIST inet-service
    type CDATA #REQUIRED
	ip NMTOKEN #IMPLIED
>

<!ATTLIST tcp
    name CDATA #REQUIRED
	value CDATA #IMPLIED
>       

<!ATTLIST service-group
	name CDATA #REQUIRED
>

<!ATTLIST service-group-member
	name CDATA #REQUIRED
>

<!ATTLIST Service-group
	name CDATA #REQUIRED
>

<!ATTLIST Server
	name CDATA #REQUIRED
>

<!ATTLIST redirector
	name ID #REQUIRED
>

<!ATTLIST ip-from
	address NMTOKEN #REQUIRED
    port NMTOKEN #REQUIRED
>

<!ATTLIST ip-to
    address NMTOKEN #REQUIRED
    port NMTOKEN #REQUIRED
>


<!ATTLIST network
  	name CDATA #IMPLIED
  	range CDATA #REQUIRED
>  

<!ATTLIST host
  	name CDATA #IMPLIED
  	ipaddress CDATA #IMPLIED
>  
  
<!ATTLIST port
  	number CDATA #REQUIRED
  	protocol CDATA #REQUIRED
>

=== rbe/dmerce/dmerce3/etc/ncc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ncc SYSTEM "ncc.dtd">
<ncc>
  <server name="www1-1">
    <interface name="eri0" ip-address="10.48.35.3" />
    <inetservice type="http" ip="">
      <tcp name="ports" value="80" />
      <tcp name="send" value="GET /\r\n\r\n" />
      <tcp name="expectContent" value="html" />
      <tcp name="noExpectContent" value="fehler" />
    </inetservice>
  </server>
  <server name="www1-2">
    <interface name="eri0" ip-address="10.48.35.3" />
    <inet-service type="http" ip="">
      <tcp name="ports" value="80" />
      <tcp name="send" value="GET /\r\n\r\n" />
      <tcp name="expectContent" value="html" />
      <tcp name="noExpectContent" value="fehler" />
    </inet-service>
  </server>
  <server name="www2">
    <interface name="eri0" ip-address="10.48.35.3" />
    <inet-service type="http" ip="">
      <tcp name="ports" value="80" />
      <tcp name="send" value="GET /\r\n\r\n" />
      <tcp name="expectContent" value="html" />
      <tcp name="noExpectContent" value="fehler" />
    </inet-service>
  </server>
  <service-group name="www1">
    <service-group-member name="www1-1" />
    <service-group-member name="www1-2" />
  </service-group>
  <monitor>
    <service-group name="www1" />
    <server name="www2" />
  </monitor>
  <redirector name="rdr1">
    <ip-from address="10.48.35.3" port="8085" />
    <ip-to address="212.128.150.71" port="80" />
  </redirector>
  <portscanner>
    <host name="" ipaddress="10.48.35.3">
      <port number="80" protocol="tcp" />
    </host>
  </portscanner>
</ncc>
