=== rbe/dmerce/dmerce3/etc/RDBD.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : DB Result.xsd
    Created on : 23. August 2003, 19:08
    Author     : Masanori Fujita
    Description:
        Purpose of XML Schema document follows.
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.wanci.com"
            xmlns="http://www.wanci.com"
            elementFormDefault="qualified">

    <xsd:element name="rdbsdata">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="meta" type="META"/>
                <xsd:element name="data" type="DATA"/>
                <xsd:element name="error" type="xsd:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:complexType name="META">
        <xsd:sequence>
            <xsd:element name="sql-statement" type="xsd:string"/>
            <xsd:element name="type-info" type="TYPEINFO"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="DATA">
        <xsd:sequence>
            <xsd:element name="row" minOccurs="0" maxOccurs="unbounded" type="ROW"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="ROW">
        <xsd:sequence>
            <xsd:element name="field" minOccurs="0" maxOccurs="unbounded" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="TYPEINFO">
        <xsd:sequence>
            <xsd:element name="column" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:attribute name="name" type="xsd:string"/>
                    <xsd:attribute name="type" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
        
</xsd:schema>

=== rbe/dmerce/dmerce3/etc/RDBDExample.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : RDBDExample.xml
    Created on : August 25, 2003, 2:44 PM
    Author     : pg
    Description:
        Purpose of the document follows.
-->

<rdbsdata xmlns='http://www.wanci.com'
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:schemaLocation='http://www.wanci.com RDBD.xsd'>
  
  <meta>
    <sql-statement>SELECT * FROM TABLE_A</sql-statement>
    <type-info>
        <column name="Feld1" type="String"/>
        <column name="Feld2" type="Integer"/>
        <column name="Feld3" type="Boolean"/>
    </type-info>
  </meta>
  <data>
    <row>
        <field>Zeile 1</field>
        <field>123</field>
        <field>true</field>
    </row>
    <row>
        <field>Zeile 2</field>
        <field>456</field>
        <field>false</field>
    </row>
  </data>
  
  <error>Fehler 1</error>

</rdbsdata>
