=== rbe/dmerce/dmerce3/etc/security.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.1ci.de"
            xmlns="http://www.1ci.de"
            elementFormDefault="qualified">

	<xsd:element name="security">
		<xsd:complexType>
            <xsd:sequence>
                <xsd:element name="login" type="login-type"/>
                <xsd:choice>
                	<xsd:element name="database-sec" type="database-sec-type"/>
                	<!-- hier können später weitere Security-Typen eingebunden werden. -->
                </xsd:choice>
                <xsd:element name="security-constraint" minOccurs="0" maxOccurs="unbounded" type="security-constraint-type"/>
            </xsd:sequence>
        </xsd:complexType>
	</xsd:element>
	
	<xsd:complexType name="login-type">
		<xsd:sequence>
			<xsd:element name="login-page" type="xsd:string"/>
			<xsd:element name="error-page" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="database-sec-type">
		<xsd:sequence>
			<xsd:element name="authentication" type="authentication-type"/>
			<xsd:element name="authorization" type="authorization-type"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="authentication-type">
		<xsd:sequence>
			<xsd:element name="table" type="xsd:string"/>
			<xsd:element name="user-column" type="xsd:string"/>
			<xsd:element name="password-column" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="authorization-type">
		<xsd:sequence>
			<xsd:element name="table" type="xsd:string"/>
			<xsd:element name="user-column" type="xsd:string"/>
			<xsd:element name="role-column" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="security-constraint-type">
		<xsd:sequence>
			<xsd:choise>
				<xsd:element name="web-resource-collection" minOccurs="1" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="web-resource-name" type="xsd:string"/>
							<xsd:element name="url-pattern" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="workflow" minOccurs="1" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:attribute name="id" type="xsd:string"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:choise>
			<xsd:element name="auth-constraint">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="role-name" minOccurs="1" maxOccurs="unbounded" type="xsd:string"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== rbe/dmerce/dmerce3/src/ant/security.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
    Document   : security.xml
    Created on : 26. Februar 2004, 11:32
    Author     : Masanori Fujita
    Description:
        Initial Draft on security.xml
-->
<!-- 
<security xmlns="http://www.1ci.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.1ci.de file:/C:/Temp/security.xsd">
-->
<security>
	<login>
		<login-page>/login/login.jsp</login-page>
		<error-page>/login/error.jsp</error-page>
	</login>
	<database-sec>
		<authentication>
			<table>user_passwort_tabelle</table>
			<user-column>userid</user-column>
			<password-column>password</password-column>
		</authentication>
		<authorization>
			<table>user_role_tabelle</table>
			<user-column>userid</user-column>
			<role-column>roleid</role-column>
		</authorization>
	</database-sec>
	<security-constraint>
		<web-resource-collection>
			<web-resource-name>Member-Bereich</web-resource-name>
			<url-pattern>/members/*</url-pattern>
		</web-resource-collection>
		<web-resource-collection>
			<web-resource-name>Noch ein Bereich</web-resource-name>
			<url-pattern>/special/*</url-pattern>
		</web-resource-collection>
		<auth-constraint>
			<role-name>member</role-name>
			<role-name>admin</role-name>
		</auth-constraint>
	</security-constraint>
	<security-constraint>
		<workflow id="register"/>
		<auth-constraint>
			<role-name>member</role-name>
			<role-name>admin</role-name>
		</auth-constraint>
	</security-constraint>
</security>
