=== rbe/dmerce/dmerce3/etc/WORKFLOWS.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--
    Version 2.1
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.1ci.de"
            xmlns="http://www.1ci.de"
            elementFormDefault="qualified">

    <xsd:element name="workflows">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="workflow" minOccurs="1" maxOccurs="unbounded" type="WORKFLOW"/>
            </xsd:sequence>
            <xsd:attribute name="version" type="xsd:float" use="required"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:complexType name="WORKFLOW">
        <xsd:sequence>
            <xsd:element name="page" minOccurs="1" maxOccurs="unbounded" type="PAGE"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string"/>
    </xsd:complexType>
    
    <xsd:complexType name="PAGE">
        <xsd:sequence>
            <xsd:element name="formmap" minOccurs="0" maxOccurs="1" type="FORMMAP"/>
            <xsd:element name="transition" minOccurs="0" maxOccurs="unbounded" type="TRANSITION"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="template" type="xsd:string" use="required"/>
        <xsd:attribute name="formid" type="xsd:string"/>
        <xsd:attribute name="editable" type="xsd:boolean"/>
    </xsd:complexType>
    
    <xsd:complexType name="PARAMETERS">
        <xsd:sequence>
            <xsd:element name="parameter" minOccurs="1" maxOccurs="unbounded" type="PARAMETER"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="TRANSITION">
        <xsd:sequence>
            <xsd:element name="condition" minOccurs="0" maxOccurs="1" type="CONDITION"/>
            <xsd:element name="action" minOccurs="0" maxOccurs="1" type="ACTION"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="url" type="xsd:string"/>
        <xsd:attribute name="target" type="xsd:string"/>
        <xsd:attribute name="validation" type="xsd:boolean" use="optional" default="true"/>
    </xsd:complexType>

    <xsd:complexType name="CONDITION">
        <xsd:sequence>
            <xsd:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="PARAMETER"/>
            <xsd:element name="formfield" minOccurs="0" maxOccurs="unbounded" type="FORMFIELD"/>
        </xsd:sequence>
        <xsd:attribute name="type" type="xsd:string"/>
        <xsd:attribute name="javaclass" type="xsd:string"/>
        <xsd:attribute name="value" type="xsd:string"/>
    </xsd:complexType>
        
    <xsd:complexType name="ACTION">
        <xsd:sequence>
            <xsd:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="PARAMETER"/>
            <xsd:element name="formfield" minOccurs="0" maxOccurs="unbounded" type="FORMFIELD"/>
        </xsd:sequence>
        <xsd:attribute name="type" type="xsd:string"/>
        <xsd:attribute name="javaclass" type="xsd:string"/>
    </xsd:complexType>
        
    <xsd:complexType name="FORMMAP">
        <xsd:sequence>
            <xsd:element name="fieldmap" minOccurs="1" maxOccurs="unbounded" type="FIELDMAP"/>
        </xsd:sequence>
        <xsd:attribute name="table" type="xsd:string" use="required"/>
        <xsd:attribute name="primarykey" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="FIELDMAP">
        <xsd:attribute name="formfield" type="xsd:string" use="required"/>
        <xsd:attribute name="dbfield" type="xsd:string" use="required"/>
        <xsd:attribute name="default" type="xsd:string"/>
        <xsd:attribute name="file" type="xsd:boolean"/>
    </xsd:complexType>
        
    <xsd:complexType name="FORMFIELD">
        <xsd:attribute name="pageid" type="xsd:string"/>
        <xsd:attribute name="formid" type="xsd:string" use="required"/>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="PARAMETER">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="value" type="xsd:string" use="required"/>
    </xsd:complexType>

</xsd:schema>

=== rbe/dmerce/dmerce3/src/applications/date/etc/workflows.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<workflows xmlns='http://www.1ci.de'
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:schemaLocation='http://www.1ci.de ../../../etc/WORKFLOWS.xsd'
  version="2.0"
>

    <workflow id="register">
    
        <page id="registerpage" template="form_register.jsp" formid="form1" editable="false">
            <formmap table="vkunde" primarykey="kundennr">
                <fieldmap formfield="name" dbfield="name"/>
                <fieldmap formfield="vorname" dbfield="vorname"/>
                <fieldmap formfield="email" dbfield="email"/>
                <fieldmap formfield="plz" dbfield="plz"/>
                <fieldmap formfield="strasse" dbfield="strasse"/>
                <fieldmap formfield="ort" dbfield="ort"/>
            </formmap>
            <transition name="call_proc" target="list">
            	<condition type="buttonpressed" value="Ok"/>
            	<action javaclass="com.wanci.examples.callproc.CallAction"/>
            </transition>
            <transition name="abort" target="list" validation="false">
            	<condition type="buttonpressed" value="Cancel"/>
            </transition>
        </page>
        
        <page id="list" template="list.jsp"/>
        
    </workflow>

</workflows>

=== rbe/dmerce/dmerce3/src/applications/callproc/etc/workflows.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<workflows xmlns='http://www.1ci.de'
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:schemaLocation='http://www.1ci.de ../../../etc/WORKFLOWS.xsd'
  version="2.0"
>

    <workflow id="register">
    
        <page id="registerpage" template="form_register.jsp" formid="form1" editable="false">
            <transition name="call_proc" target="list">
            	<condition type="buttonpressed" value="Ok"/>
            	<action type="callproc">
            		<parameter name="name" value="NEW_KUNDE"/>
					<formfield formid="form1" name="name"/>
					<formfield formid="form1" name="vorname"/>
					<formfield formid="form1" name="email"/>
            	</action>
            </transition>
            <transition name="abort" target="list" validation="false">
            	<condition type="buttonpressed" value="Cancel"/>
            </transition>
        </page>
        
        <page id="list" template="list.jsp"/>
        
    </workflow>

</workflows>

=== rbe/dmerce/dmerce3/src/applications/1dsl/etc/workflows.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<workflows xmlns='http://www.1ci.de'
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:schemaLocation='http://www.1ci.de ../../../etc/WORKFLOWS.xsd'
  version="2.0"
>

<workflow id="creg">

		<page id="register" template="creg_insert.jsp"
			formid="customer" editable="false">

			<formmap table="t_customer" primarykey="ID">
				<fieldmap formfield="gender" dbfield="gender"/>
				<fieldmap formfield="lastname" dbfield="lastname"/>
				<fieldmap formfield="firstname" dbfield="firstname"/>
				<fieldmap formfield="street" dbfield="street"/>
				<fieldmap formfield="zipcode" dbfield="zipcode"/>
				<fieldmap formfield="city" dbfield="city"/>
				<fieldmap formfield="phone" dbfield="phone"/>
				<fieldmap formfield="email" dbfield="email"/>
				<fieldmap formfield="birthday" dbfield="birthday"/>
				<fieldmap formfield="accountnumber" dbfield="accountnumber"/>
				<fieldmap formfield="accountowner" dbfield="accountowner"/>
				<fieldmap formfield="bankcode" dbfield="bankcode"/>
				<fieldmap formfield="bank" dbfield="bank"/>
				<fieldmap formfield="tacread" dbfield="tacread"/>
				<fieldmap formfield="rowread" dbfield="rowread"/>
				<fieldmap formfield="desiredstartdate" dbfield="desiredstartdate"/>

			</formmap>

			<transition name="save_to_db" target="creg_thankyou">
				<condition type="buttonpressed" value="Anmelden"/>
				<action type="callproc">
					<parameter name="name" value="sp_createcustomer"/>
					<formfield formid="customer" name="gender"/>
					<formfield formid="customer" name="lastname"/>
					<formfield formid="customer" name="firstname"/>
					<formfield formid="customer" name="street"/>
					<formfield formid="customer" name="zipcode"/>
					<formfield formid="customer" name="city"/>
					<formfield formid="customer" name="phone"/>
					<formfield formid="customer" name="email"/>
					<formfield formid="customer" name="birthday"/>
					<formfield formid="customer" name="accountnumber"/>
					<formfield formid="customer" name="accountowner"/>
					<formfield formid="customer" name="bankcode"/>
					<formfield formid="customer" name="bank"/>
					<formfield formid="customer" name="tacread"/>
					<formfield formid="customer" name="rowread"/>
					<formfield formid="customer" name="desiredstartdate"/>
                                 </action>
			</transition>

			<transition name="abort" target="creg_thankyou">
				<condition type="buttonpressed" value="Cancel"/>
			</transition>

		</page>

		<page id="creg_thankyou" template="creg_thankyou.jsp"/>

	</workflow>

<workflow id="cedit">

		<page id="register" template="cedit_maintain.jsp"
			formid="customer" editable="true">

			<formmap table="t_customer" primarykey="ID">
				<fieldmap formfield="gender" dbfield="gender"/>
				<fieldmap formfield="lastname" dbfield="lastname"/>
				<fieldmap formfield="firstname" dbfield="firstname"/>
				<fieldmap formfield="street" dbfield="street"/>
				<fieldmap formfield="zipcode" dbfield="zipcode"/>
				<fieldmap formfield="city" dbfield="city"/>
				<fieldmap formfield="phone" dbfield="phone"/>
				<fieldmap formfield="email" dbfield="email"/>
				<fieldmap formfield="birthday" dbfield="birthday"/>
				<fieldmap formfield="accountnumber" dbfield="accountnumber"/>
				<fieldmap formfield="accountowner" dbfield="accountowner"/>
				<fieldmap formfield="bankcode" dbfield="bankcode"/>
				<fieldmap formfield="bank" dbfield="bank"/>
				<fieldmap formfield="tacread" dbfield="tacread"/>
				<fieldmap formfield="rowread" dbfield="rowread"/>
				<fieldmap formfield="desiredstartdate" dbfield="desiredstartdate"/>
                <fieldmap formfield="statusid" dbfield="statusid"/>
                <fieldmap formfield="remarks" dbfield="remarks"/>
			</formmap>

			<transition name="save_to_db" target="creg_thankyou">
				<condition type="buttonpressed" value="Anmelden"/>
				<action type="callproc">
					<parameter name="name" value="sp_createcustomer"/>
					<formfield formid="customer" name="gender"/>
					<formfield formid="customer" name="lastname"/>
					<formfield formid="customer" name="firstname"/>
					<formfield formid="customer" name="street"/>
					<formfield formid="customer" name="zipcode"/>
					<formfield formid="customer" name="city"/>
					<formfield formid="customer" name="phone"/>
					<formfield formid="customer" name="email"/>
					<formfield formid="customer" name="birthday"/>
					<formfield formid="customer" name="accountnumber"/>
					<formfield formid="customer" name="accountowner"/>
					<formfield formid="customer" name="bankcode"/>
					<formfield formid="customer" name="bank"/>
					<formfield formid="customer" name="tacread"/>
					<formfield formid="customer" name="rowread"/>
					<formfield formid="customer" name="desiredstartdate"/>
                    <formfield formid="customer" name="statusid"/>
                    <formfield formid="customer" name="remarks"/>
				</action>
			</transition>

			<transition name="abort" target="cedit_list">
				<condition type="buttonpressed" value="Cancel"/>
			</transition>

		</page>

		<page id="cedit_list" template="cedit_list.jsp"/>

	</workflow>

</workflows>

=== rbe/dmerce/dmerce3/src/applications/listbox/etc/workflows.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<workflows xmlns='http://www.1ci.de'
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:schemaLocation='http://www.1ci.de ../../../etc/WORKFLOWS.xsd'
  version="2.0"
>

    <workflow id="listbox">
    
        <page
        	id="listboxformular"
			template="form_listbox.jsp"
			formid="listboxform"
			editable="true">
			
            <formmap table="vkunde" primarykey="kundennr">
                <fieldmap formfield="name" dbfield="name"/>
                <fieldmap formfield="vorname" dbfield="vorname"/>
                <fieldmap formfield="email" dbfield="email"/>
                <fieldmap formfield="plz" dbfield="plz"/>
                <fieldmap formfield="strasse" dbfield="strasse"/>
                <fieldmap formfield="ort" dbfield="ort"/>
                <fieldmap formfield="hobby" dbfield="hobby"/>
            </formmap>
            
            <transition name="save_to_db" target="list">
            	<condition type="buttonpressed" value="Ok"/>
            	<action type="maintain">
                    <formfield formid="listboxform" name="name"/>
                    <formfield formid="listboxform" name="vorname"/>
                    <formfield formid="listboxform" name="email"/>
                    <formfield formid="listboxform" name="plz"/>
                    <formfield formid="listboxform" name="strasse"/>
                    <formfield formid="listboxform" name="ort"/>
                    <formfield formid="listboxform" name="hobby"/>
				</action>
            </transition>
            
            <transition name="abort" target="list" validation="false">
            	<condition type="buttonpressed" value="Cancel"/>
            </transition>
            
        </page>
        
        <page id="list" template="list.jsp"/>
        
    </workflow>

</workflows>

=== rbe/dmerce/dmerce3/src/applications/vwclubms/etc/workflows.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<workflows xmlns='http://www.1ci.de'
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:schemaLocation='http://www.1ci.de ../WORKFLOWS.xsd'
  version="2.0"
>

          <workflow id="1cs_advert">

                    <page id="create" template="vwcreateadvertentry.jsp" formid="1cs_adverts">

                          <formmap table="t_adverts" primarykey="id">
                              <fieldmap formfield="advertcategoryid" dbfield="advertcategoriesid"/>
                              <fieldmap formfield="realname" dbfield="realname"/>
                              <fieldmap formfield="email" dbfield="email"/>
                              <fieldmap formfield="url" dbfield="url"/>
                              <fieldmap formfield="description" dbfield="description"/>
                              <fieldmap formfield="text" dbfield="text"/>
                              <fieldmap formfield="foto" dbfield="foto" file="true"/>
                          </formmap>

                          <transition name="ok" target="list" validation="true">
                             <condition type="buttonpressed" value="Anzeige aufgeben"/>

                             <action type="maintain">
                                     <formfield formid="1cs_advert" name="advertcategoryid"/>
                                     <formfield formid="1cs_advert" name="realname"/>
                                     <formfield formid="1cs_advert" name="email"/>
                                     <formfield formid="1cs_advert" name="url"/>
                                     <formfield formid="1cs_advert" name="description"/>
                                     <formfield formid="1cs_advert" name="text"/>
                                     <formfield formid="1cs_advert" name="foto"/>
                             </action>
                          </transition>

                          <transition name="cancel" target="list" validation="false">
                             <condition type="buttonpressed" value="Zurück"/>
                          </transition>

                    </page>

                    <page id="list" template="vwlistadvertcats.jsp"/>

          </workflow>

          <workflow id="1cs_appointments">

                    <page id="create" template="vwcreateappointmententry.jsp" formid="1cs_appointments">

			      <formmap table="t_appointments" primarykey="id">
				          <fieldmap formfield="dateofappointment" dbfield="dateofappointment"/>
				          <fieldmap formfield="description" dbfield="description"/>
				          <fieldmap formfield="url" dbfield="url"/>
				          <fieldmap formfield="email" dbfield="email"/>
				          <fieldmap formfield="phone" dbfield="phone"/>
				          <fieldmap formfield="realname" dbfield="realname"/>
			  </formmap>

                          <transition name="ok" target="list" validation="true">
                             <condition type="buttonpressed" value="Termin eintragen"/>
                             <action type="maintain">
                                     <formfield formid="1cs_appointments" name="dateofappointment" dbfield="dateofappointment"/>
                                     <formfield formid="1cs_appointments" name="description" dbfield="description"/>
                                     <formfield formid="1cs_appointments" name="url" dbfield="url"/>
                                     <formfield formid="1cs_appointments" name="email" dbfield="email"/>
                                     <formfield formid="1cs_appointments" name="phone" dbfield="phone"/>
                                     <formfield formid="1cs_appointments" name="realname" dbfield="realname"/>
                             </action>
                          </transition>

                          <transition name="cancel" target="list" validation="false">
                             <condition type="buttonpressed" value="Zurück"/>
                          </transition>

                    </page>

                    <page id="list" template="vwlistappointments.jsp"/>

          </workflow>

          <workflow id="1cs_guestbook">

		    <page id="create" template="vwcreateguestbookentry.jsp" formid="1cs_guestbook">

			  <formmap table="t_guestbook" primarykey="id">
                             <fieldmap formfield="realname" dbfield="realname"/>
                             <fieldmap formfield="email" dbfield="email"/>
                             <fieldmap formfield="url" dbfield="url"/>
                             <fieldmap formfield="text" dbfield="text"/>
                          </formmap>

                          <transition name="ok" target="list" validation="true">
                             <condition type="buttonpressed" value="Eintragen"/>
                             <action type="maintain">
                                     <formfield formid="1cs_guestbook" name="realname" dbfield="realname"/>
                                     <formfield formid="1cs_guestbook" name="email" dbfield="email"/>
                                     <formfield formid="1cs_guestbook" name="url" dbfield="url"/>
                                     <formfield formid="1cs_guestbook" name="text" dbfield="text"/>
                             </action>
                          </transition>

                          <transition name="cancel" target="list" validation="false">
                             <condition type="buttonpressed" value="Zurück"/>
                          </transition>

                    </page>

                    <page id="list" template="vwlistguestbook.jsp"/>

          </workflow>

          <workflow id="1cs_links">

		    <page id="create" template="vwcreatelinkentry.jsp" formid="1cs_links">

			  <formmap table="t_links" primarykey="id">
                             <fieldmap formfield="linkcategoryid" dbfield="linkcategoryid"/>
                             <fieldmap formfield="realname" dbfield="realname"/>
                             <fieldmap formfield="name" dbfield="name"/>
                             <fieldmap formfield="email" dbfield="email"/>
                             <fieldmap formfield="description" dbfield="description"/>
                             <fieldmap formfield="url" dbfield="url"/>
                          </formmap>

                          <transition name="ok" target="list" validation="true">
                             <condition type="buttonpressed" value="Eintragen"/>
                             <action type="callproc">
                                     <parameter name="name" value="sp_createlink"/>
                                     <formfield formid="1cs_links" name="linkcategoryid"/>
                                     <formfield formid="1cs_links" name="realname"/>
                                     <formfield formid="1cs_links" name="email"/>
                                     <formfield formid="1cs_links" name="name"/>
                                     <formfield formid="1cs_links" name="description"/>
                                     <formfield formid="1cs_links" name="url"/>
                             </action>
                          </transition>

                          <transition name="cancel" target="list" validation="false">
                             <condition type="buttonpressed" value="Zurück"/>
                          </transition>

                    </page>

               <page id="list" template="vwlistlinkscats.jsp"/>

          </workflow>

          <workflow id="vwadmin_advertcats">

                    <page id="create" template="vwadmin_create_advertcat.jsp" formid="vwadmin_advertcats" editable="true">

                          <formmap table="t_advertcategories" primarykey="id">
                             <fieldmap formfield="name" dbfield="name"/>
                             <fieldmap formfield="description" dbfield="description"/>
                          </formmap>

                          <transition name="ok" target="list" validation="true">
                             <condition type="buttonpressed" value="OK"/>
                             <action type="maintain">
                                     <formfield formid="vwadmin_advertcats" name="name" dbfield="name"/>
                                     <formfield formid="vwadmin_advertcats" name="description" dbfield="description"/>
                             </action>
                          </transition>

                          <transition name="cancel" target="list" validation="false">
                             <condition type="buttonpressed" value="Cancel"/>
                          </transition>

                    </page>

                    <page id="list" editable="false" template="vwadmin_list_advertcats.jsp"/>

          </workflow>

</workflows>

=== rbe/dmerce/dmerce3/src/applications/fileupload/etc/workflows.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<workflows xmlns='http://www.1ci.de'
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:schemaLocation='http://www.1ci.de ../../../etc/WORKFLOWS.xsd'
  version="2.0"
>

    <workflow id="register">
    
        <page
        	id="registerpage"
			template="form_register.jsp"
			formid="form1"
			editable="true">
			
            <formmap table="vkunde" primarykey="kundennr">
                <fieldmap formfield="name" dbfield="name"/>
                <fieldmap formfield="vorname" dbfield="vorname"/>
                <fieldmap formfield="email" dbfield="email"/>
                <fieldmap formfield="plz" dbfield="plz"/>
                <fieldmap formfield="strasse" dbfield="strasse"/>
                <fieldmap formfield="ort" dbfield="ort"/>
                <fieldmap formfield="foto" dbfield="filename_foto" file="true"/>
            </formmap>
            
            <transition name="save_to_db" target="list">
            	<condition type="buttonpressed" value="Ok"/>
            	<action type="maintain">
                    <formfield formid="form1" name="name"/>
                    <formfield formid="form1" name="vorname"/>
                    <formfield formid="form1" name="email"/>
                    <formfield formid="form1" name="plz"/>
                    <formfield formid="form1" name="strasse"/>
                    <formfield formid="form1" name="ort"/>
                    <formfield formid="form1" name="foto"/>
				</action>
            </transition>
            
            <transition name="abort" target="list" validation="false">
            	<condition type="buttonpressed" value="Cancel"/>
            </transition>
            
        </page>
        
        <page id="list" template="list.jsp"/>
        
    </workflow>

</workflows>

=== rbe/dmerce/dmerce3/src/applications/multiple/etc/workflows.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<workflows xmlns='http://www.1ci.de'
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:schemaLocation='http://www.1ci.de ../../../etc/WORKFLOWS.xsd'
  version="2.0"
>

    <workflow id="register">
    
        <page id="registerpage1" template="form_register_p1.jsp" formid="form1" editable="true">
            <formmap table="vkunde" primarykey="kundennr">
                <fieldmap formfield="name" dbfield="name"/>
                <fieldmap formfield="vorname" dbfield="vorname"/>
                <fieldmap formfield="email" dbfield="email"/>
            </formmap>
            <transition name="nextpage" target="registerpage2">
            	<condition type="buttonpressed" value="Ok"/>
            </transition>
            <transition name="abort" target="list" validation="false">
            	<condition type="buttonpressed" value="Cancel"/>
            </transition>
        </page>
        
        <page id="registerpage2" template="form_register_p2.jsp" formid="form1" editable="true">
            <formmap table="vkunde" primarykey="kundennr">
                <fieldmap formfield="plz" dbfield="plz"/>
                <fieldmap formfield="strasse" dbfield="strasse"/>
                <fieldmap formfield="ort" dbfield="ort"/>
            </formmap>
            <transition name="save_to_db" target="list">
            	<condition type="buttonpressed" value="Ok"/>
            	<action type="maintain">
                    <formfield pageid="registerpage1" formid="form1" name="name"/>
                    <formfield pageid="registerpage1" formid="form1" name="vorname"/>
                    <formfield pageid="registerpage1" formid="form1" name="email"/>
                    <formfield formid="form1" name="plz"/>
                    <formfield formid="form1" name="strasse"/>
                    <formfield formid="form1" name="ort"/>
				</action>
            </transition>
            <transition name="abort" target="list" validation="false">
            	<condition type="buttonpressed" value="Cancel"/>
            </transition>
        </page>
        
        <page id="list" template="list.jsp"/>
        
    </workflow>

</workflows>
