=== rbe/dmerce/dmerce3/testresources/serverliste.dtd
<!ELEMENT serverliste (server+)>

  <!ELEMENT server (url?, protocol?, host?, path?, file+, port?, user?, password?)>
  <!ELEMENT url EMPTY>
  <!ELEMENT protocol EMPTY>
  <!ELEMENT host EMPTY>
  <!ELEMENT path EMPTY>
  <!ELEMENT file EMPTY>
  <!ELEMENT port EMPTY>
  <!ELEMENT user EMPTY>
  <!ELEMENT password EMPTY>
  
  <!ATTLIST server
  		name CDATA #REQUIRED
  >
  <!ATTLIST url
  		value CDATA #REQUIRED
  >
  <!ATTLIST protocol
  		value CDATA #REQUIRED
  >
  <!ATTLIST host 
  		value CDATA #REQUIRED
  >
  <!ATTLIST path
  		value CDATA #IMPLIED
  >
  <!ATTLIST file
  		value CDATA #IMPLIED
  >
  <!ATTLIST port
  		value CDATA #REQUIRED
  >
  <!ATTLIST username
  		value CDATA #IMPLIED
  >
  <!ATTLIST password
  		value CDATA #IMPLIED
  >

=== rbe/dmerce/dmerce3/testresources/serverliste.xml
<?xml version='1.0' encoding="UTF-8"?>

<!DOCTYPE serverliste SYSTEM "serverliste.dtd">

<serverliste>

	<server name="www.host.sk">
		<url value="http://www.magni.host.sk/pics/magni_main_bg.jpg"/>
		<protocol value="http"/>
		<host value="www.magni.host.sk"/>		
		<path value="pics"/>
		<file value="magni_main_bg.jpg"/>
		<port value="80"/>
	</server>
	
	<server name="ftp.host.sk">
		<url value="ftp://ftp.host.sk/"/>
		<protocol value="ftp"/>
		<host value="ftp.host.sk"/>
		<path value="pics"/>		
		<file value="matrix2.jpg"/>
		<port value="21"/>
		<username value="magni"/>
		<password value="********"/>
	</server>
	
</serverliste>
