=== rbe/dmerce/dmerce3/src/doku/FORMS.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.1ci.de"
            xmlns="http://www.1ci.de"
            elementFormDefault="qualified">

    <xsd:element name="forms">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="form" minOccurs="1" maxOccurs="unbounded" type="FORM"/>
            </xsd:sequence>
            <xsd:attribute name="version" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:complexType name="FORM">
        <xsd:sequence>
            <xsd:element name="name" minOccurs="1" maxOccurs="1" type="xsd:string"/>
            <xsd:element name="description" minOccurs="1" maxOccurs="1" type="xsd:string"/>
            <xsd:element name="formversion" minOccurs="0" maxOccurs="1" type="xsd:string"/>
            <xsd:element name="field" minOccurs="0" maxOccurs="unbounded" type="FIELD"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string"/>
    </xsd:complexType>
    
    <xsd:complexType name="FIELD">
        <xsd:sequence>
            <xsd:element name="description" minOccurs="1" maxOccurs="1" type="xsd:string"/>
            <xsd:element name="type" minOccurs="1" maxOccurs="1" type="xsd:string"/>
            <xsd:element name="displaytype" minOccurs="0" maxOccurs="1" type="xsd:string"/>
            <xsd:element name="options" minOccurs="0" maxOccurs="1" type="OPTIONS"/>
            <xsd:element name="constraints" minOccurs="0" maxOccurs="1" type="CONSTRAINTS"/>
            <xsd:element name="messages" minOccurs="0" maxOccurs="1" type="MESSAGES"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="required" type="xsd:boolean"/>
    </xsd:complexType>
    
    <xsd:complexType name="CONSTRAINTS">
    	<xsd:sequence>
	    	<xsd:element name="constraint" minOccurs="0" maxOccurs="unbounded" type="CONSTRAINT"/>
	    </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="CONSTRAINT">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="type">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:NMTOKEN">
                            <xsd:enumeration value="minlength"/>
                            <xsd:enumeration value="maxlength"/>
                            <xsd:enumeration value="mininclusive"/>
                            <xsd:enumeration value="maxinclusive"/>
                            <xsd:enumeration value="precision"/>
                            <xsd:enumeration value="scale"/>
                            <xsd:enumeration value="startdate"/>
                            <xsd:enumeration value="enddate"/>
                            <xsd:enumeration value="format"/>                            
                            <xsd:enumeration value="minselected"/>
                            <xsd:enumeration value="maxselected"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:attribute>
                <xsd:attribute name="description" type="xsd:string"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="MESSAGES">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="error" minOccurs="0" maxOccurs="unbounded" type="xsd:string"/>
            <xsd:element name="warning" minOccurs="0" maxOccurs="unbounded" type="xsd:string"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="OPTIONS">
        <xsd:sequence>
            <xsd:element name="option" minOccurs="0" maxOccurs="unbounded" type="OPTION"/>
        </xsd:sequence>
        <xsd:attribute name="sql" type="xsd:string"/>
        <xsd:attribute name="sqlkey" type="xsd:string"/>
        <xsd:attribute name="sqlvalue" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="OPTION">
     <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="key" type="xsd:string" />
      </xsd:extension>
     </xsd:simpleContent>
    </xsd:complexType>


    <xsd:complexType name="PERIOD">
        <xsd:sequence>
            <xsd:element name="startdate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
            <xsd:element name="enddate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
        </xsd:sequence>
    </xsd:complexType>
        
</xsd:schema>

=== rbe/dmerce/dmerce3/src/applications/vwclubms/etc/forms.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<forms xmlns="http://www.1ci.de"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.1ci.de ../FORMS.xsd">

     <form id="1cs_adverts">

          <name>Adverts - 1Ci(R) Community Services</name>
          <description>Manage advertisements in your web application</description>
          <formversion>1.0</formversion>

          <field name="advertcategoryid" required="true">
               <description></description>
               <type>number</type>
          </field>

          <field name="realname" required="true">
               <description></description>
               <type>string</type>
          </field>

          <field name="email" required="true">
               <description></description>
               <type>string</type>
               <constraints>
                  <constraint type="format" description="alias@domain.tld">.+@.+\.\w{2,4}</constraint>
               </constraints>
          </field>

          <field name="url">
               <description></description>
               <type>string</type>
               <constraints>
                  <constraint type="format" description="www.domain.tld (ohne http://)">\w+\..+\.\w{2,4}</constraint>
               </constraints>
          </field>

          <field name="description" required="true">
               <description></description>
               <type>string</type>
          </field>

          <field name="text" required="true">
               <description></description>
               <type>string</type>
          </field>

          <field name="foto">
                <description></description>
                <type>file</type>
          </field>

     </form>

     <!-- Appointments

     SQL> desc t_appointments
     Name                  Null?    Type
     ID                          NOT NULL NUMBER(1)
     ACTIVE                   NOT NULL NUMBER(1)
     CREATEDDATETIME                   TIMESTAMP(6)
     DATEOFAPPOINTMENT          NOT NULL TIMESTAMP(6)
     DESCRIPTION          NOT NULL VARCHAR2(250)
     URL                           VARCHAR2(50)
     EMAIL                  NOT NULL VARCHAR2(50)
     PHONE                           VARCHAR2(50)

     -->
     <form id="1cs_appointments">

          <name>Appointments - 1Ci(R) Community Services</name>
          <description>Manage appointments in your web application</description>
          <formversion>1.0</formversion>

          <field name="dateofappointment" required="true">
               <description></description>
               <type>date</type>
               <displayformat>dd.MM.yyyy</displayformat>
          </field>

          <field name="description" required="true">
               <description></description>
               <type>string</type>
          </field>

          <field name="url">
               <description></description>
               <type>string</type>
               <constraints>
                  <constraint type="format" description="www.domain.tld (ohne http://)">\w+\..+\.\w{2,4}</constraint>
               </constraints>
          </field>

          <field name="email" required="true">
               <description></description>
               <type>string</type>
               <constraints>
                  <constraint type="format" description="alias@domain.tld">.+@.+\..+</constraint>
               </constraints>
          </field>

          <field name="phone">
              <description></description>
              <type>string</type>
          </field>

          <field name="realname" required="true">
              <description></description>
              <type>string</type>
          </field>

     </form>

     <!-- A guest book

     SQL> desc t_guestbook
     Name                      Null?    Type
     ID                              NOT NULL  NUMBER(1)
     ACTIVE                      NOT NULL  NUMBER(1)
     CREATEDDATETIME                        TIMESTAMP(6)
     REALNAME                      NOT NULL  VARCHAR2(50)
     EMAIL                      NOT NULL  VARCHAR2(50)
     URL                                 VARCHAR2(50)
     TEXT                      NOT NULL  VARCHAR2(250)

     -->
     <form id="1cs_guestbook">

          <name>Guestbook - 1Ci(R) Community Services</name>
          <description>Entries in a guestbook for your website</description>
          <formversion>1.0</formversion>

          <field name="realname" required="true">
               <description></description>
               <type>string</type>
          </field>

          <field name="email" required="true">
               <description></description>
               <type>string</type>
               <constraints>
                  <constraint type="format" description="alias@domain.tld">.+@.+\..+</constraint>
               </constraints>
          </field>

          <field name="url">
               <description></description>
               <type>string</type>
               <constraints>
                  <constraint type="format" description="www.domain.tld (ohne http://)">\w+\..+\.\w{2,4}</constraint>
               </constraints>
          </field>

          <field name="text" required="true">
               <description></description>
               <type>string</type>
          </field>

     </form>

     <!-- Links

     SQL> desc t_linkcategories
     Name                         Null?    Type
     ID                                  NOT NULL NUMBER(1)
     ACTIVE                           NOT NULL NUMBER(1)
     CREATEDDATETIME                           TIMESTAMP(6)
     NAME                          NOT NULL VARCHAR2(50)
     DESCRIPTION                  NOT NULL VARCHAR2(250)

     SQL> desc t_links
     Name                          Null?    Type
     ID                                  NOT NULL NUMBER(1)
     ACTIVE                           NOT NULL NUMBER(1)
     CREATEDDATETIME                           TIMESTAMP(6)
     LINKCATEGORIESID                  NOT NULL NUMBER
     NEW                          NOT NULL NUMBER(1)
     NAME                          NOT NULL VARCHAR2(50)
     DESCRIPTION                  NOT NULL VARCHAR2(250)
     URL                          NOT NULL VARCHAR2(50)
     HITS                                   NUMBER

     -->
     <form id="1cs_linkcategories">

          <name>Link categories - 1Ci(R) Community Services</name>
          <description>Manage categories for links in your web application</description>
          <formversion>1.0</formversion>

          <field name="name" required="true">
               <description></description>
               <type>string</type>
          </field>

          <field name="description" required="true">
               <description></description>
               <type>string</type>
          </field>

     </form>

     <form id="1cs_links">

          <name>Links - 1Ci(R) Community Services</name>
          <description>Manage link lists in your web application</description>
          <formversion>1.0</formversion>

          <field name="linkcategoryid" required="true">
               <description></description>
               <type>string</type>
          </field>

          <field name="realname">
               <description></description>
               <type>string</type>
          </field>

          <field name="email">
               <description></description>
               <type>string</type>
          </field>

          <field name="name" required="true">
               <description></description>
               <type>string</type>
          </field>

          <field name="description" required="true">
               <description></description>
               <type>string</type>
          </field>

          <field name="url" required="true">
               <description></description>
               <type>string</type>
               <constraints>
                  <constraint type="format" description="www.domain.tld (ohne http://)">\w+\..+\.\w{2,4}</constraint>
               </constraints>
          </field>

     </form>

     <form id="vwadmin_advertcats">

           <name>List Advert Categories</name>
           <description>ListAdvert Categories</description>
           <formversion>1.0</formversion>

           <field name="name" required="true">
               <description></description>
               <type>string</type>
           </field>

           <field name="description" required="true">
               <description></description>
               <type>string</type>
           </field>

     </form>

</forms>

=== rbe/dmerce/dmerce3/src/doku/etc/forms.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<forms xmlns="http://www.1ci.de"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.1ci.de ../FORMS.xsd">
	<form id="login">
		<name>loginform</name>
		<description>Formular zum einloggen</description>
		<formversion>0.1</formversion>
		<field name="name" required="true">
			<description>Name</description>
			<type>string</type>
		</field>
		<field name="passwort">
			<description>Passwort</description>
			<type>string</type>
		</field>
	</form>
	<form id="form1">
		<name>registerform</name>
		<description>Formular zum registrieren</description>
		<formversion>0.1</formversion>
		<field name="name" required="true">
			<description>Name</description>
			<type>string</type>
		</field>
		<field name="vorname" required="true">
			<description>Vorname</description>
			<type>string</type>
		</field>
		<field name="email" required="true">
			<description>Email</description>
			<type>string</type>
			<constraints>
				<constraint type="format">.+@.+\..+</constraint>
			</constraints>
		</field>
		<field name="strasse">
			<description>Strasse</description>
			<type>string</type>
		</field>
		<field name="plz">
			<description>PLZ</description>
			<type>string</type>
			<constraints>
				<constraint type="format" description="xxxxx">\d{5}</constraint>
			</constraints>
		</field>
		<field name="ort">
			<description>Ort</description>
			<type>string</type>
		</field>
		<field name="telefon">
			<description>Telefon</description>
			<type>string</type>
		</field>
		<field name="comment">
			<description>Kommentar</description>
			<type>string</type>
		</field>
		<field name="agb">
			<description>agb</description>
			<type>boolean</type>
			<displaytype>radio</displaytype>
		</field>
		<field name="gender">
			<description>Anrede</description>
			<type>string</type>
			<options>
				<option key="m">Herr</option>
				<option key="w">Frau</option>
			</options>
		</field>
		<field name="country">
			<description>Land</description>
			<type>string</type>
			<constraints>
				<constraint type="minselected">0</constraint>
				<constraint type="maxselected">1</constraint>
			</constraints>
		</field>
		<field name="hobby">
			<description>Hobbys (max 2 von 4 auswählen)</description>
			<type>string</type>
			<options>
				<option key="surfen">Surfen</option>
				<option key="reiten">Reiten</option>
				<option key="fussball">Fußball</option>
				<option key="tennis">Tennis</option>
			</options>
			<constraints>
				<constraint type="minselected">0</constraint>
				<constraint type="maxselected">2</constraint>
			</constraints>
		</field>
		<field name="kunden">
			<description>Kunden</description>
			<type>list</type>
			<options sql="select * from vkunde" sqlkey="kundennr"
				sqlvalue="name"/>
		</field>
	</form>
	<!-- Formular für eine Beispielanwendung -->
	<form id="einladung">
		<name>Rückmeldung</name>
		<description>Formular für die Rückmeldung zur Party</description>
		<formversion>1.0</formversion>
		<field name="name" required="true">
			<description>Name</description>
			<type>string</type>
		</field>
		<field name="telefon">
			<description>Telefon</description>
			<type>string</type>
		</field>
		<field name="teilnahme">
			<description>Rückmeldung</description>
			<type>string</type>
			<options keytype="string">
				<option key="komme">Ich komme.</option>
				<option key="kann nicht">Ich kann nicht kommen.</option>
				<option key="komme mit begleitung">Ich komme mit Begleitung.</option>
			</options>
			<constraints>
				<constraint type="minselected">1</constraint>
				<constraint type="maxselected">1</constraint>
			</constraints>
		</field>
		<field name="trinken">
			<description>Autofahrer?</description>
			<type>number</type>
			<options>
				<option key="1">Ich muss nicht fahren (und kann daher trinken).</option>
				<option key="2">Ich muss fahren und kann deswegen nicht trinken.</option>
				<option key="3">Ich muss zwar nicht fahren, will aber trotzdem
					nicht trinken.</option>
				<option key="4">Ich muss fahren, will aber trotzdem trinken.</option>
			</options>
			<constraints>
				<constraint type="minselected">1</constraint>
				<constraint type="maxselected">1</constraint>
			</constraints>
		</field>
		<field name="trinken2">
			<description>Autofahrer?</description>
			<type>number</type>
			<options>
				<option key="1">Sie/Er muss nicht fahren (und kann daher
					trinken).</option>
				<option key="2">Sie/Er muss fahren und kann deswegen nicht
					trinken.</option>
				<option key="3">Sie/Er muss zwar nicht fahren, will aber
					trotzdem nicht trinken.</option>
				<option key="4">Sie/Er muss fahren, will aber trotzdem trinken.</option>
			</options>
			<constraints>
				<constraint type="minselected">1</constraint>
				<constraint type="maxselected">1</constraint>
			</constraints>
		</field>
		<field name="bier">
			<description>Bier</description>
			<type>boolean</type>
		</field>
		<field name="wein">
			<description>Wein</description>
			<type>boolean</type>
		</field>
		<field name="hartes">
			<description>Hartes Gesöff</description>
			<type>boolean</type>
		</field>
		<field name="soft">
			<description>Alkoholfreie Getränke</description>
			<type>boolean</type>
		</field>
	</form>
</forms>

=== rbe/dmerce/dmerce3/src/applications/fileupload/etc/forms.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<forms xmlns="http://www.1ci.de"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.1ci.de ../../../etc/FORMS.xsd">

	<form id="form1">
		<name>registerform</name>
		<description>Formular zum registrieren</description>
		<formversion>0.1</formversion>
		<field name="name" required="true">
			<description>Name</description>
			<type>string</type>
		</field>
		<field name="vorname" required="true">
			<description>Vorname</description>
			<type>string</type>
		</field>
		<field name="email" required="true">
			<description>Email</description>
			<type>string</type>
			<constraints>
				<constraint type="format">.+@.+\..+</constraint>
			</constraints>
		</field>
		<field name="strasse">
			<description>Strasse</description>
			<type>string</type>
		</field>
		<field name="plz">
			<description>PLZ</description>
			<type>string</type>
			<constraints>
				<constraint type="format" description="xxxxx">\d{5}</constraint>
			</constraints>
		</field>
		<field name="ort">
			<description>Ort</description>
			<type>string</type>
		</field>
		<field name="foto">
			<description>Passfoto</description>
			<type>file</type>
		</field>
	</form>
	
</forms>
