=== rbe/dmerce/dmerce3/src/doku/FORMS.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.1ci.de"
            xmlns="http://www.1ci.de"
            elementFormDefault="qualified">

    <xsd:element name="forms">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="form" minOccurs="1" maxOccurs="unbounded" type="FORM"/>
            </xsd:sequence>
            <xsd:attribute name="version" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:complexType name="FORM">
        <xsd:sequence>
            <xsd:element name="name" minOccurs="1" maxOccurs="1" type="xsd:string"/>
            <xsd:element name="description" minOccurs="1" maxOccurs="1" type="xsd:string"/>
            <xsd:element name="formversion" minOccurs="0" maxOccurs="1" type="xsd:string"/>
            <xsd:element name="field" minOccurs="0" maxOccurs="unbounded" type="FIELD"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string"/>
    </xsd:complexType>
    
    <xsd:complexType name="FIELD">
        <xsd:sequence>
            <xsd:element name="description" minOccurs="1" maxOccurs="1" type="xsd:string"/>
            <xsd:element name="type" minOccurs="1" maxOccurs="1" type="xsd:string"/>
            <xsd:element name="displaytype" minOccurs="0" maxOccurs="1" type="xsd:string"/>
            <xsd:element name="options" minOccurs="0" maxOccurs="1" type="OPTIONS"/>
            <xsd:element name="constraints" minOccurs="0" maxOccurs="1" type="CONSTRAINTS"/>
            <xsd:element name="messages" minOccurs="0" maxOccurs="1" type="MESSAGES"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="required" type="xsd:boolean"/>
    </xsd:complexType>
    
    <xsd:complexType name="CONSTRAINTS">
    	<xsd:sequence>
	    	<xsd:element name="constraint" minOccurs="0" maxOccurs="unbounded" type="CONSTRAINT"/>
	    </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="CONSTRAINT">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="type">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:NMTOKEN">
                            <xsd:enumeration value="minlength"/>
                            <xsd:enumeration value="maxlength"/>
                            <xsd:enumeration value="mininclusive"/>
                            <xsd:enumeration value="maxinclusive"/>
                            <xsd:enumeration value="precision"/>
                            <xsd:enumeration value="scale"/>
                            <xsd:enumeration value="startdate"/>
                            <xsd:enumeration value="enddate"/>
                            <xsd:enumeration value="format"/>                            
                            <xsd:enumeration value="minselected"/>
                            <xsd:enumeration value="maxselected"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:attribute>
                <xsd:attribute name="description" type="xsd:string"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="MESSAGES">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="error" minOccurs="0" maxOccurs="unbounded" type="xsd:string"/>
            <xsd:element name="warning" minOccurs="0" maxOccurs="unbounded" type="xsd:string"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="OPTIONS">
        <xsd:sequence>
            <xsd:element name="option" minOccurs="0" maxOccurs="unbounded" type="OPTION"/>
        </xsd:sequence>
        <xsd:attribute name="sql" type="xsd:string"/>
        <xsd:attribute name="sqlkey" type="xsd:string"/>
        <xsd:attribute name="sqlvalue" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="OPTION">
     <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="key" type="xsd:string" />
      </xsd:extension>
     </xsd:simpleContent>
    </xsd:complexType>


    <xsd:complexType name="PERIOD">
        <xsd:sequence>
            <xsd:element name="startdate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
            <xsd:element name="enddate" minOccurs="0" maxOccurs="1" type="xsd:date"/>
        </xsd:sequence>
    </xsd:complexType>
        
</xsd:schema>

=== rbe/dmerce/dmerce3/src/applications/1cs/etc/forms.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<forms xmlns="http://www.1ci.de"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.1ci.de ../FORMS.xsd">

     <form id="1cs_adverts">

          <name>Adverts - 1Ci(R) Community Services</name>
          <description>Manage advertisements in your web application</description>
          <formversion>1.0</formversion>

          <field name="advertcategoryid" required="true">
               <description>Category of advertisement</description>
	       <type>list</type>
	       <options sql="SELECT id, name FROM t_advertcategories ORDER BY name" sqlkey="id" sqlvalue="name"/>
          </field>

          <field name="advertcategoryid2">
               <description>Category of advertisement</description>
	       <type>string</type>
          </field>

          <field name="realname" required="true">
               <description>Real name</description>
               <type>string</type>
          </field>

          <field name="email" required="true">
               <description>Email address</description>
               <type>string</type>
               <constraints>
                  <constraint type="format" description="alias@domain.tld">.+@.+\..+</constraint>
               </constraints>
          </field>

          <field name="url">
               <description>URL</description>
               <type>string</type>
               <constraints>
                  <constraint type="format" description="www.domain.tld (ohne http://)">\w+\..+\.\w{2,4}</constraint>
               </constraints>
          </field>

          <field name="description" required="true">
               <description>Short description</description>
               <type>string</type>
          </field>

          <field name="text" required="true">
               <description>Text</description>
               <type>string</type>
          </field>

          <field name="foto">
                <description>Foto</description>
                <type>file</type>
          </field>

          <field name="foto_original">
                <description>Foto</description>
                <type>string</type>
          </field>

          <field name="foto_server">
                <description>Foto</description>
                <type>string</type>
          </field>

     </form>

     <!-- Appointments

     SQL> desc t_appointments
     Name                  Null?    Type
     ID                          NOT NULL NUMBER(1)
     ACTIVE                   NOT NULL NUMBER(1)
     CREATEDDATETIME                   TIMESTAMP(6)
     DATEOFAPPOINTMENT          NOT NULL TIMESTAMP(6)
     DESCRIPTION          NOT NULL VARCHAR2(250)
     URL                           VARCHAR2(50)
     EMAIL                  NOT NULL VARCHAR2(50)
     PHONE                           VARCHAR2(50)

     -->
     <form id="1cs_appointments">

          <name>Appointments - 1Ci(R) Community Services</name>
          <description>Manage appointments in your web application</description>
          <formversion>1.0</formversion>

          <field name="dateofappointment" required="true">
               <description>Date of appointment</description>
               <type>string</type>
               <constraints>
                  <constraint type="format" description="TT.MM.JJJJ">\d{2}\.\d{2}\.\d{4}</constraint>
               </constraints>
          </field>

          <field name="description" required="true">
               <description>Detailed description of appointment</description>
               <type>string</type>
          </field>

          <field name="url">
               <description>URL</description>
               <type>string</type>
               <constraints>
                  <constraint type="format" description="www.domain.tld (ohne http://)">\w+\..+\.\w{2,4}</constraint>
               </constraints>
          </field>

          <field name="email" required="true">
               <description>Email-address of main contact</description>
               <type>string</type>
               <constraints>
                  <constraint type="format" description="alias@domain.tld">.+@.+\..+</constraint>
               </constraints>
          </field>

          <field name="phone">
              <description>Phone number of main contact</description>
              <type>string</type>
          </field>

          <field name="realname" required="true">
              <description>Real name of main contact</description>
              <type>string</type>
          </field>

     </form>

     <!-- A guest book

     SQL> desc t_guestbook
     Name                      Null?    Type
     ID                              NOT NULL  NUMBER(1)
     ACTIVE                      NOT NULL  NUMBER(1)
     CREATEDDATETIME                        TIMESTAMP(6)
     REALNAME                      NOT NULL  VARCHAR2(50)
     EMAIL                      NOT NULL  VARCHAR2(50)
     URL                                 VARCHAR2(50)
     TEXT                      NOT NULL  VARCHAR2(250)

     -->
     <form id="1cs_guestbook">

          <name>Guestbook - 1Ci(R) Community Services</name>
          <description>Entries in a guestbook for your website</description>
          <formversion>1.0</formversion>

          <field name="realname" required="true">
               <description>Your real name</description>
               <type>string</type>
          </field>

          <field name="email" required="true">
               <description>Email of author</description>
               <type>string</type>
               <constraints>
                  <constraint type="format" description="alias@domain.tld">.+@.+\..+</constraint>
               </constraints>
          </field>

          <field name="url">
               <description>URL of author</description>
               <type>string</type>
               <constraints>
                  <constraint type="format" description="www.domain.tld (ohne http://)">\w+\..+\.\w{2,4}</constraint>
               </constraints>
          </field>

          <field name="text" required="true">
               <description>Comment</description>
               <type>string</type>
          </field>

     </form>

     <!-- Links

     SQL> desc t_linkcategories
     Name                         Null?    Type
     ID                                  NOT NULL NUMBER(1)
     ACTIVE                           NOT NULL NUMBER(1)
     CREATEDDATETIME                           TIMESTAMP(6)
     NAME                          NOT NULL VARCHAR2(50)
     DESCRIPTION                  NOT NULL VARCHAR2(250)

     SQL> desc t_links
     Name                          Null?    Type
     ID                                  NOT NULL NUMBER(1)
     ACTIVE                           NOT NULL NUMBER(1)
     CREATEDDATETIME                           TIMESTAMP(6)
     LINKCATEGORIESID                  NOT NULL NUMBER
     NEW                          NOT NULL NUMBER(1)
     NAME                          NOT NULL VARCHAR2(50)
     DESCRIPTION                  NOT NULL VARCHAR2(250)
     URL                          NOT NULL VARCHAR2(50)
     HITS                                   NUMBER

     -->
     <form id="1cs_linkcategories">

          <name>Link categories - 1Ci(R) Community Services</name>
          <description>Manage categories for links in your web application</description>
          <formversion>1.0</formversion>

          <field name="name" required="true">
               <description>Name of a link category</description>
               <type>string</type>
          </field>

          <field name="description" required="true">
               <description>Detailed description of a link category</description>
               <type>string</type>
          </field>

     </form>

     <form id="1cs_links">

          <name>Links - 1Ci(R) Community Services</name>
          <description>Manage link lists in your web application</description>
          <formversion>1.0</formversion>

          <field name="linkcategoryid" required="true">
               <description></description>
               <type>string</type>
          </field>

          <field name="realname">
               <description></description>
               <type>string</type>
          </field>

          <field name="email">
               <description></description>
               <type>string</type>
          </field>

          <field name="name" required="true">
               <description></description>
               <type>string</type>
          </field>

          <field name="description" required="true">
               <description></description>
               <type>string</type>
          </field>

          <field name="url" required="true">
               <description></description>
               <type>string</type>
               <constraints>
                  <constraint type="format" description="www.domain.tld (ohne http://)">\w+\..+\.\w{2,4}</constraint>
               </constraints>
          </field>

     </form>

     <form id="vwadmin_advertcats">

           <name>List Advert Categories</name>
           <description>ListAdvert Categories</description>
           <formversion>1.0</formversion>

           <field name="name" required="true">
               <description>Name of Advert Category</description>
               <type>string</type>
           </field>

           <field name="description" required="true">
               <description>Description of Advert Category</description>
               <type>string</type>
           </field>

     </form>

</forms>

=== rbe/dmerce/dmerce3/src/applications/listbox/etc/forms.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<forms xmlns="http://www.1ci.de"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.1ci.de ../../../etc/FORMS.xsd">

	<form id="listboxform">
		<name>listboxformular</name>
		<description>Formular zum Ausw‰hlen aus einer Liste</description>
		<formversion>0.1</formversion>
		<field name="name" required="true">
			<description>Name</description>
			<type>string</type>
		</field>
		<field name="vorname" required="true">
			<description>Vorname</description>
			<type>string</type>
		</field>
		<field name="email" required="true">
			<description>Email</description>
			<type>string</type>
			<constraints>
				<constraint type="format">.+@.+\..+</constraint>
			</constraints>
		</field>
		<field name="strasse">
			<description>Strasse</description>
			<type>string</type>
		</field>
		<field name="plz">
			<description>PLZ</description>
			<type>string</type>
			<constraints>
				<constraint type="format" description="xxxxx">\d{5}</constraint>
			</constraints>
		</field>
		<field name="ort">
			<description>Ort</description>
			<type>string</type>
		</field>
		<field name="hobby">
    		<description>Hobbys</description>
		    <type>string</type>
		    <options>
			    <option key="surfen">Surfen</option>
				<option key="reiten">Reiten</option>
				<option key="fussball">Fuﬂball</option>
				<option key="tennis">Tennis</option>
			</options>
        	<constraints>
			    <constraint type="minselected">0</constraint>
			    <constraint type="maxselected">4</constraint>
    		</constraints>
		</field>
		<field name="foto">
			<description>Foto</description>
			<type>file</type>
		</field>
	</form>
</forms>

=== rbe/dmerce/dmerce3/applications/ncc/forms.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<forms xmlns="http://www.1ci.de"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.1ci.de ../../../etc/FORMS.xsd">

        <form id="dnszonesns">
        <name></name>
                <description></description>
                <formversion>0.1</formversion>

                <field name="id" required="true">
                        <description>id</description>
                        <type>number</type>
                </field>
                <field name="position" required="true">
                        <description>position</description>
                        <type>number</type>
                </field>
                <field name="dnszonesid" required="true">
                        <description>dnszonesid</description>
                        <type>number</type>
                </field>
                <field name="dnsnsid" required="true">
                        <description>dnsnsid</description>
                        <type>number</type>
                </field>
        </form>

        <form id="dnszones">
        <name></name>
                <description></description>
                <formversion>0.1</formversion>

                <field name="id" required="true">
                        <description>id</description>
                        <type>number</type>
                </field>
                <field name="active" required="true">
                        <description>active</description>
                        <type>number</type>
                </field>
                <field name="name" required="true">
                        <description>name</description>
                        <type>string</type>
                </field>
                <field name="soaserial" required="true">
                        <description>soaserial</description>
                        <type>date</type>
                </field>
                <field name="soasubserial" required="true">
                        <description>soasubserial</description>
                        <type>number</type>
                </field>
                <field name="soarefresh" required="true">
                        <description>soarefresh</description>
                        <type>number</type>
                </field>
                <field name="soaretry" required="true">
                        <description>soaretry</description>
                        <type>number</type>
                </field>
                <field name="soaexpire" required="true">
                        <description>soaexpire</description>
                        <type>number</type>
                </field>
                <field name="soamaximum" required="true">
                        <description>soaserial</description>
                        <type>number</type>
                </field>
                <field name="ttl" required="true">
                        <description>ttl</description>
                        <type>number</type>
                </field>
                <field name="legalpersonid" required="true">
                        <description>legalpersonid</description>
                        <type>number</type>
                </field>
                <field name="admincpersonid" required="true">
                        <description>admincpersonid</description>
                        <type>number</type>
                </field>
                <field name="zonecpersonid" required="true">
                        <description>zonecpersonid</description>
                        <type>number</type>
                </field>
                <field name="techcpersonid" required="true">
                        <description>techcpersonid</description>
                        <type>number</type>
                </field>
                <field name="validfrom" required="true">
                        <description>validfrom</description>
                        <type>date</type>
                </field>
                <field name="validuntil" required="true">
                        <description>validfrom</description>
                        <type>date</type>
                </field>
        </form>

        <form id="dnsrrtypes">
        <name></name>
                <description></description>
                <formversion>0.1</formversion>

                <field name="id" required="true">
                        <description>id</description>
                        <type>number</type>
                </field>
                <field name="name" required="true">
                        <description>name</description>
                        <type>string</type>
                </field>
        </form>

        <form id="dnsrecords">
        <name></name>
                <description></description>
                <formversion>0.1</formversion>

                <field name="id" required="true">
                        <description>id</description>
                        <type>number</type>
                </field>
                <field name="dnszoneid" required="true">
                        <description>dnszoneid</description>
                        <type>number</type>
                </field>
                <field name="active" required="true">
                        <description>active</description>
                        <type>number</type>
                </field>
                <field name="name" required="true">
                        <description>name</description>
                        <type>string</type>
                </field>
                <field name="type" required="true">
                        <description>type</description>
                        <type>number</type>
                </field>
                <field name="mxprio" required="true">
                        <description>mxprio</description>
                        <type>number</type>
                </field>
                <field name="value" required="true">
                        <description>value</description>
                        <type>string</type>
                </field>
                <field name="ptr" required="true">
                        <description>ptr</description>
                        <type>number</type>
                </field>
                <field name="validfrom" required="true">
                        <description>validfrom</description>
                        <type>date</type>
                </field>
                <field name="validuntil" required="true">
                        <description>validuntil</description>
                        <type>date</type>
                </field>
        </form>

        <form id="dnsns">
        <name></name>
                <description></description>
                <formversion>0.1</formversion>

                <field name="id" required="true">
                        <description>id</description>
                        <type>number</type>
                </field>
                <field name="name" required="true">
                        <description>name</description>
                        <type>string</type>
                </field>
                <field name="ipaddress" required="true">
                        <description>ipaddress</description>
                        <type>string</type>
                </field>
        </form>

        <form id="dnslistenon">
        <name></name>
                <description></description>
                <formversion>0.1</formversion>

                <field name="id" required="true">
                        <description>id</description>
                        <type>number</type>
                </field>
                <field name="dnsnsid" required="true">
                        <description>dnsnsid</description>
                        <type>number</type>
                </field>
                <field name="ipaddress" required="true">
                        <description>ipaddress</description>
                        <type>string</type>
                </field>
        </form>

        <form id="dnshandles">
        <name></name>
                <description></description>
                <formversion>0.1</formversion>

                <field name="id" required="true">
                        <description>id</description>
                        <type>number</type>
                </field>
                <field name="dnsnsid" required="true">
                        <description>dnsnsid</description>
                        <type>number</type>
                </field>
                <field name="handle" required="true">
                        <description>handle</description>
                        <type>string</type>
                </field>
                <field name="comments" required="true">
                        <description>comments</description>
                        <type>string</type>
                </field>
        </form>

        <form id="dnsforwarders">
        <name></name>
                <description></description>
                <formversion>0.1</formversion>

                <field name="id" required="true">
                        <description>id</description>
                        <type>number</type>
                </field>
                <field name="dnsnsid" required="true">
                        <description>dnsnsid</description>
                        <type>number</type>
                </field>
                <field name="ip" required="true">
                        <description>ip</description>
                        <type>string</type>
                </field>
        </form>

</forms>
